/**
 * Read-only access to the bundled MCP data index.
 *
 * The files are generated by `scripts/build-mcp-data.ts` into `data/` (a sibling
 * of `dist/`) and shipped with the package. Everything is loaded lazily from
 * disk and cached for the lifetime of the process.
 */

import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const PACKAGE_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const DATA_DIR = join(PACKAGE_ROOT, "data");

export interface PackageIndexEntry {
  name: string;
  description: string;
  version?: string;
  url: string;
  symbolCount: number;
}

export interface SearchEntry {
  package: string;
  name: string;
  kind: string;
  summary: string;
  url: string;
}

export interface MemberData {
  name: string;
  kind: string;
  summary: string;
}

export interface SymbolData {
  name: string;
  kind: string;
  summary: string;
  comment: string;
  url: string;
  source?: string;
  members?: MemberData[];
}

export interface PackageData {
  package: string;
  description: string;
  version?: string;
  url: string;
  symbols: Record<string, SymbolData>;
}

function readJsonFile<T>(path: string): T | undefined {
  if (!existsSync(path)) return undefined;
  try {
    return JSON.parse(readFileSync(path, "utf8")) as T;
  } catch {
    return undefined;
  }
}

let indexCache: { packages: PackageIndexEntry[] } | undefined;
export function loadIndex(): { packages: PackageIndexEntry[] } | undefined {
  indexCache ??= readJsonFile<{ packages: PackageIndexEntry[] }>(join(DATA_DIR, "index.json"));
  return indexCache;
}

let searchCache: SearchEntry[] | undefined;
export function loadSearch(): SearchEntry[] | undefined {
  searchCache ??= readJsonFile<SearchEntry[]>(join(DATA_DIR, "search.json"));
  return searchCache;
}

const packageCache = new Map<string, PackageData | undefined>();
export function loadPackage(pkg: string): PackageData | undefined {
  if (!packageCache.has(pkg)) {
    packageCache.set(pkg, readJsonFile<PackageData>(join(DATA_DIR, "packages", `${pkg}.json`)));
  }
  return packageCache.get(pkg);
}

export function loadGuide(pkg: string): string | undefined {
  const path = join(DATA_DIR, "packages", pkg, "guide.md");
  if (!existsSync(path)) return undefined;
  return readFileSync(path, "utf8");
}

export function serverVersion(): string {
  const pkg = readJsonFile<{ version?: string }>(join(PACKAGE_ROOT, "package.json"));
  return pkg?.version ?? "0.0.0";
}
