/* eslint-disable @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-return */
/**
 * FROST(secp256k1, SHA-256) with Taproot keys, key generation, key shares.
 *
 * This module provides types and functions for FROST key generation
 * and management, including trusted dealer key generation, DKG,
 * key refresh, and repairable threshold schemes.
 *
 * It also includes the EvenY and Tweak traits for BIP-340/341 compatibility.
 *
 * @module keys
 */

import type { Secp256K1Sha256TRImpl } from "../index.js";
import type { RandomSource, IdentifierList as CoreIdentifierList } from "@frosts/core";
import {
  type KeyPackage as CoreKeyPackage,
  type PublicKeyPackage as CorePublicKeyPackage,
  type SecretShare as CoreSecretShare,
  type SigningShare as CoreSigningShare,
  type VerifyingShare as CoreVerifyingShare,
  type VerifiableSecretSharingCommitment as CoreVerifiableSecretSharingCommitment,
  generateWithDealer as coreGenerateWithDealer,
  splitFromScalar as coreSplitFromScalar,
  reconstruct as coreReconstruct,
  SigningKey as CoreSigningKey,
} from "@frosts/core";

import {
  Secp256K1Sha256TR as _Secp256K1Sha256TR,
  Secp256K1Group,
  Secp256K1ScalarField,
  hasEvenY,
  intoEvenY as _intoEvenY,
  tweak as computeTweak,
  type EvenY,
  type Tweak,
} from "../index.js";

// Re-use the ciphersuite type
type S = Secp256K1Sha256TRImpl;

/** A FROST(secp256k1, SHA-256) with Taproot signing key */
export type SigningKey = CoreSigningKey<S>;

/**
 * The identifier list to use when generating key shares.
 */
export type IdentifierList = CoreIdentifierList<S>;

/**
 * Secret and public key material generated by a dealer performing
 * {@link generateWithDealer}.
 *
 * # Security
 *
 * To derive a FROST(secp256k1, SHA-256) with Taproot keypair, the receiver of the {@link SecretShare} *must* call
 * `toKeyPackage()`, which under the hood also performs validation.
 */
export type SecretShare = CoreSecretShare<S>;

/**
 * A secret scalar value representing a signer's share of the group secret.
 */
export type SigningShare = CoreSigningShare<S>;

/**
 * A public group element that represents a single signer's public verification share.
 */
export type VerifyingShare = CoreVerifyingShare<S>;

/**
 * A FROST(secp256k1, SHA-256) with Taproot keypair, which can be generated either by a trusted dealer or using
 * a DKG.
 *
 * When using a central dealer, {@link SecretShare}s are distributed to
 * participants, who then perform verification, before deriving
 * {@link KeyPackage}s, which they store to later use during signing.
 */
export type KeyPackage = CoreKeyPackage<S>;

/**
 * Public data that contains all the signers' public keys as well as the
 * group public key.
 *
 * Used for verification purposes before publishing a signature.
 */
export type PublicKeyPackage = CorePublicKeyPackage<S>;

/**
 * Contains the commitments to the coefficients for our secret polynomial _f_,
 * used to generate participants' key shares.
 *
 * {@link VerifiableSecretSharingCommitment} contains a set of commitments to the coefficients (which
 * themselves are scalars) for a secret polynomial f, where f is used to
 * generate each ith participant's key share f(i). Participants use this set of
 * commitments to perform verifiable secret sharing.
 *
 * Note that participants MUST be assured that they have the *same*
 * {@link VerifiableSecretSharingCommitment}, either by performing pairwise comparison, or by using
 * some agreed-upon public location for publication, where each participant can
 * ensure that they received the correct (and same) value.
 */
export type VerifiableSecretSharingCommitment = CoreVerifiableSecretSharingCommitment<S>;

// Re-export EvenY and Tweak traits
export type { EvenY, Tweak };

/**
 * Allows all participants' keys to be generated using a central, trusted
 * dealer.
 *
 * @param ciphersuite - The Secp256K1Sha256TR ciphersuite instance
 * @param maxSigners - Maximum number of signers
 * @param minSigners - Minimum number of signers (threshold)
 * @param identifiers - Identifier list configuration
 * @param rng - Random number generator
 * @returns A Promise of a tuple of [Map of SecretShares by identifier string, PublicKeyPackage]
 * @throws {FrostError} If parameters are invalid
 */
export async function generateWithDealer(
  ciphersuite: S,
  maxSigners: number,
  minSigners: number,
  identifiers: IdentifierList,
  rng: RandomSource,
): Promise<[Map<string, SecretShare>, PublicKeyPackage]> {
  return coreGenerateWithDealer(ciphersuite, maxSigners, minSigners, identifiers, rng);
}

/**
 * Splits an existing key into FROST shares.
 *
 * This is identical to {@link generateWithDealer} but receives an existing key
 * instead of generating a fresh one. This is useful in scenarios where
 * the key needs to be generated externally or must be derived from e.g. a
 * seed phrase.
 *
 * @param ciphersuite - The Secp256K1Sha256TR ciphersuite instance
 * @param secret - The secret signing key to split
 * @param maxSigners - Maximum number of signers
 * @param minSigners - Minimum number of signers (threshold)
 * @param identifiers - Identifier list configuration
 * @param rng - Random number generator
 * @returns A Promise of a tuple of [Map of SecretShares by identifier string, PublicKeyPackage]
 * @throws {FrostError} If parameters are invalid
 */
export async function split(
  ciphersuite: S,
  secret: SigningKey,
  maxSigners: number,
  minSigners: number,
  identifiers: IdentifierList,
  rng: RandomSource,
): Promise<[Map<string, SecretShare>, PublicKeyPackage]> {
  return coreSplitFromScalar(ciphersuite, secret.toScalar(), maxSigners, minSigners, identifiers, rng);
}

/**
 * Recompute the secret from t-of-n secret shares using Lagrange interpolation.
 *
 * This can be used if for some reason the original key must be restored; e.g.
 * if threshold signing is not required anymore.
 *
 * This is NOT required to sign with FROST; the whole point of FROST is being
 * able to generate signatures only using the shares, without having to
 * reconstruct the original key.
 *
 * The caller is responsible for providing at least `minSigners` shares;
 * if less than that is provided, a different key will be returned.
 *
 * @param ciphersuite - The Secp256K1Sha256TR ciphersuite instance
 * @param keyPackages - Array of key packages
 * @returns The reconstructed SigningKey
 * @throws {FrostError} If reconstruction fails
 */
export function reconstruct(ciphersuite: S, keyPackages: KeyPackage[]): SigningKey {
  const scalar = coreReconstruct(ciphersuite, keyPackages);
  return CoreSigningKey.fromScalar(ciphersuite, scalar);
}

// ---------------------------------------------------------------------------
// EvenY Implementation for PublicKeyPackage
// ---------------------------------------------------------------------------

/**
 * Check if a PublicKeyPackage has an even Y coordinate verifying key.
 */
export function publicKeyPackageHasEvenY(pkg: PublicKeyPackage): boolean {
  return hasEvenY(pkg.verifyingKey as Uint8Array);
}

/**
 * Convert a PublicKeyPackage to have an even Y coordinate verifying key.
 */
export function publicKeyPackageIntoEvenY(
  pkg: PublicKeyPackage,
  isEven?: boolean,
): PublicKeyPackage {
  const evenY = isEven ?? publicKeyPackageHasEvenY(pkg);
  if (!evenY) {
    const verifyingKey = Secp256K1Group.negate(pkg.verifyingKey as Uint8Array);
    const verifyingShares = new Map<string, Uint8Array>();
    for (const [id, share] of pkg.verifyingShares) {
      verifyingShares.set(id, Secp256K1Group.negate(share as Uint8Array));
    }
    return {
      ...pkg,
      verifyingKey,
      verifyingShares,
    } as PublicKeyPackage;
  }
  return pkg;
}

/**
 * Apply a Taproot tweak to a PublicKeyPackage.
 */
export function publicKeyPackageTweak(
  pkg: PublicKeyPackage,
  merkleRoot?: Uint8Array,
): PublicKeyPackage {
  // First ensure even Y
  const evenPkg = publicKeyPackageIntoEvenY(pkg, undefined);

  // Compute tweak
  const t = computeTweak(evenPkg.verifyingKey as Uint8Array, merkleRoot);
  const tp = Secp256K1Group.basePointMul(t);

  // Apply tweak to verifying key and all shares
  const verifyingKey = Secp256K1Group.add(evenPkg.verifyingKey as Uint8Array, tp);
  const verifyingShares = new Map<string, Uint8Array>();
  for (const [id, share] of evenPkg.verifyingShares) {
    verifyingShares.set(id, Secp256K1Group.add(share as Uint8Array, tp));
  }

  return {
    ...evenPkg,
    verifyingKey,
    verifyingShares,
  } as PublicKeyPackage;
}

// ---------------------------------------------------------------------------
// EvenY Implementation for KeyPackage
// ---------------------------------------------------------------------------

/**
 * Check if a KeyPackage has an even Y coordinate verifying key.
 */
export function keyPackageHasEvenY(pkg: KeyPackage): boolean {
  return hasEvenY(pkg.verifyingKey as Uint8Array);
}

/**
 * Convert a KeyPackage to have an even Y coordinate verifying key.
 */
export function keyPackageIntoEvenY(pkg: KeyPackage, isEven?: boolean): KeyPackage {
  const evenY = isEven ?? keyPackageHasEvenY(pkg);
  if (!evenY) {
    const verifyingKey = Secp256K1Group.negate(pkg.verifyingKey as Uint8Array);
    const signingShare = Secp256K1ScalarField.negate(pkg.signingShare as bigint);
    const verifyingShare = Secp256K1Group.negate(pkg.verifyingShare as Uint8Array);
    return {
      ...pkg,
      verifyingKey,
      signingShare,
      verifyingShare,
    } as KeyPackage;
  }
  return pkg;
}

/**
 * Apply a Taproot tweak to a KeyPackage.
 */
export function keyPackageTweak(pkg: KeyPackage, merkleRoot?: Uint8Array): KeyPackage {
  // First ensure even Y
  const evenPkg = keyPackageIntoEvenY(pkg, undefined);

  // Compute tweak
  const t = computeTweak(evenPkg.verifyingKey as Uint8Array, merkleRoot);
  const tp = Secp256K1Group.basePointMul(t);

  // Apply tweak to all components
  const verifyingKey = Secp256K1Group.add(evenPkg.verifyingKey as Uint8Array, tp);
  const signingShare = Secp256K1ScalarField.add(evenPkg.signingShare as bigint, t);
  const verifyingShare = Secp256K1Group.add(evenPkg.verifyingShare as Uint8Array, tp);

  return {
    ...evenPkg,
    verifyingKey,
    signingShare,
    verifyingShare,
  } as KeyPackage;
}

// Re-export submodules
export * as dkg from "./dkg.js";
export * as refresh from "./refresh.js";
export * as repairable from "./repairable.js";
