import { defineConfig } from "tsdown";

// A small Node CLI: a single ESM bundle with a shebang, no runtime dependencies.
// The TypeDoc-derived data it serves lives in the sibling `data/` directory
// (generated by `scripts/build-mcp-data.ts` and read at runtime).
export default defineConfig({
  entry: ["src/index.ts"],
  format: ["esm"],
  dts: false,
  clean: true,
  treeshake: true,
  sourcemap: false,
  minify: false,
  target: "es2022",
  outDir: "dist",
  platform: "node",
});
